---
description: Add basic schema structure
migrations:
  - migrate: > 
      CREATE TABLE IF NOT EXISTS todos (
        id VARCHAR(50) PRIMARY KEY,
        summary TEXT,
        done BOOLEAN
      )
    rollback: DROP TABLE IF EXISTS todos
