---
service:
  port: 8080
  url: http://localhost:8080
storage:
  # supported types are memory and sql
  type: memory
  # provider: postgresql
  # config:
  #   host: host.docker.internal
  #   port: 5432
  #   user: todo
  #   password: todo
  #   dbname: todo
  #   schema: todo
  # provider: mysql
  # config:
  #   host: host.docker.internal
  #   port: 3306
  #   user: todo
  #   password: todo
  #   dbname: todo
  #   schema: todo
  # provider: sqlite
  # config:
  #   path: todo.sqlite
leadership:
  # specify the interval to update node heartbeat
  heartbeat: 60s
health:
  # if true, readiness checks will check the health of the configured storage adapter
  storage: true
  # list of dependency URLs. If not empty will perform a GET request for each URL
  # and fail the readiness check if any fail or return a status code > 399
  dependencies: ~
logger:
  level: info
  json: false