---
service:
  port: 8080
  url: http://localhost:8080
storage:
  # supported types are memory and sql
  type: memory
  # provider: postgresql
  # config:
  #   host: host.docker.internal
  #   port: 5432
  #   user: todo
  #   password: todo
  #   dbname: todo
  #   schema: todo
  # provider: mysql
  # config:
  #   host: host.docker.internal
  #   port: 3306
  #   user: todo
  #   password: todo
  #   dbname: todo
  #   schema: todo
  # provider: sqlite
  # config:
  #   path: todo.db
leadership:
  # specify the interval to update node heartbeat
  heartbeat_interval: 60s
