---
description: Create the todos table
migrations:
  - migrate: >
      CREATE TABLE IF NOT EXISTS todos (
        id TEXT PRIMARY KEY,
        summary TEXT NOT NULL,
        done INTEGER NOT NULL DEFAULT 0
      )
    rollback: DROP TABLE IF EXISTS todos
