name: default 

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-latest # TODO: Choose a better image (or not)
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./... 
  conventional-commits:
     runs-on: ubuntu-latest
     permissions:
      actions: read
      contents: write
      issues: read
      packages: write
      pull-requests: read
     steps:
      - name: Conventional Commits Action
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, for private repositories.
          allowed-commit-types: "feat,fix,cicd,chore,patch,release,test,docs" # Optional, set if you want a subset of commit types to be allowed.
